index:
   path: /
   controller: App\Controller\MainController::mainResponse
api:
   path: /api
   controller: App\Controller\MainController::mainResponse
   defaults: { _format: json }
   requirements:
      _format: json
generate:
   path: /api/generate
   controller: App\Controller\MainController::generate
   defaults: { _format: json }
   requirements:
      _format: json
retrieveUrl:
   path: /api/{uri}
   controller: App\Controller\MainController::retrieveUrl
   defaults: { _format: json }
   requirements:
      _format: json
redirectTo:
   path: /{uri}
   controller: App\Controller\MainController::redirectTo